blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from body.views import (
    frontpage_view,
    authors_view,
    login_view,
    register_view,
    favourites_view,
    account_view,
    logout_view,
    newpost_view,
    latestposts_view,
    post_view,
    private_post_view,
    tag_posts_view,
    search_view,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', frontpage_view, name='frontpage'),
    path('authors/', authors_view, name='authors'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('favourites/', favourites_view, name='favourites'),
    path('account/', account_view, name='account'),
    path('logout/', logout_view, name='logout'),
    path('newpost/', newpost_view, name='newpost'),
    path('latestposts/', latestposts_view, name='latestposts'),
    path('post/<slug:slug>/', post_view, name='post'),
    path('post/private/<slug:slug>/', private_post_view, name='private_post'),
    path('tag/<str:tag_name>/', tag_posts_view, name='tag_posts'),
    path('search/', search_view, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/body/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')
    nickname = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.user.username if self.user else 'No user'
    
class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_added_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(unique=True)
    PRIVACY_CHOICES = [
        ('public', 'Public'),
        ('private', 'Private'),
    ]
    privacy = models.CharField(max_length=10, choices=PRIVACY_CHOICES, default='public')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=30, blank=True, null=True)
    content = models.TextField()
    comment_added_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-comment_added_date']

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

blog/body/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Post, Tag, Comment
from django.contrib.auth import authenticate

User = get_user_model()

class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email', max_length=50)
    nickname = forms.CharField(label='Nickname', max_length=30)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return confirm_password
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already in use.")
        return username
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    class Meta:
        model = User
        fields = ('username', 'email', 'nickname', 'password',)

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    def authenticate_user(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        return user
    
class NewPostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'tags']

    def save(self, commit=True):
        post = super().save(commit=False)
        if commit:
            post.save()
        return post

    def save_m2m(self):
        post = self.instance
        tags = self.cleaned_data['tags']
        post.tags.set(tags)

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ('content',)

blog/body/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegistrationForm, UserLoginForm, NewPostForm, CommentForm
from .models import UserProfile, Post, Tag, Comment
from django.utils import timezone
from django.core.paginator import Paginator
from django.utils.text import slugify
from django.http import HttpResponseForbidden
from django.db.models import Q 

def register_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user, nickname=form.cleaned_data['nickname'])
            messages.success(request, 'Registration successful. You can now log in.')
            return redirect('login')
        else:
            error_message = 'Invalid registration data'
            return render(request, 'register.html', {'form': form, 'error_message': error_message})
    else:
        form = UserRegistrationForm()
    return render(request, 'register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You have been successfully logged in.')
                return redirect('frontpage')
        messages.error(request, 'Invalid username or password')
    else:
        form = UserLoginForm()
    return render(request, 'login.html', {'form': form})

@login_required
def account_view(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile(user=request.user, nickname="ADMIN")
    registration_date = request.user.date_joined
    registration_date = timezone.localtime(registration_date)
    context = {
        'user_profile': user_profile,
        'registration_date': registration_date,
    }
    return render(request, 'account.html', context)

@login_required
def logout_view(request):
    logout(request)
    return redirect('frontpage')

def frontpage_view(request):
    is_user_logged_in = request.user.is_authenticated
    random_post = None

    if is_user_logged_in:
        last_post_id = request.session.get('last_post_id')
        posts_query = Post.objects.filter(Q(privacy='private') | Q(privacy='public'), image__isnull=False)
        if last_post_id:
            posts_query = posts_query.exclude(id=last_post_id)

        random_post = posts_query.order_by('?').first()
    else:
        last_post_id = request.session.get('last_post_id')
        posts_query = Post.objects.filter(privacy='public', image__isnull=False)
        if last_post_id:
            posts_query = posts_query.exclude(id=last_post_id)

        random_post = posts_query.order_by('?').first()

    if random_post:
        request.session['last_post_id'] = random_post.id
    else:
        request.session['last_post_id'] = None

    context = {
        'is_user_logged_in': is_user_logged_in,
        'random_post': random_post,
    }
    return render(request, 'frontpage.html', context)

@login_required
def newpost_view(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.slug = slugify(post.title)

            image_file = request.FILES.get('image')
            if image_file:
                post.image = image_file

            privacy_field = request.POST.get('privacy')
            post.privacy = privacy_field
            post.save()
            form.save_m2m()

            return redirect('latestposts')
    else:
        form = NewPostForm()

    tags = Tag.objects.all()

    is_public = True
    if request.method == 'GET' and 'privacy' in request.GET:
        privacy_field = request.GET.get('privacy')
        if privacy_field == 'Private':
            is_public = False

    return render(request, 'newpost.html', {'form': form, 'tags': tags, 'is_public': is_public})

def tag_posts_view(request, tag_name):
    tag = Tag.objects.get(name=tag_name)
    posts = tag.post_set.all().order_by('-post_added_date')
    paginator = Paginator(posts, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'tag': tag.name,
        'posts': page_obj,
    }

    return render(request, 'tag_posts.html', context)

def authors_view(request):
    return render(request, 'authors.html')

def favourites_view(request):
    return render(request, 'favourites.html')

def latestposts_view(request):
    all_posts = Post.objects.filter(Q(privacy='public') | Q(privacy='private')).order_by('-post_added_date')
    paginator = Paginator(all_posts, 9)
    page_number = request.GET.get('page')
    latest_posts = paginator.get_page(page_number)

    is_user_logged_in = request.user.is_authenticated

    context = {
        'latestposts': latest_posts,
        'is_user_logged_in': is_user_logged_in,
    }
    return render(request, 'latestposts.html', context)

def login_required_for_comment(user):
    return user.is_authenticated

def post_view(request, slug):
    post = get_object_or_404(Post, slug=slug)
    is_public = post.privacy == 'public'

    if not is_public and not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            if hasattr(request.user, 'userprofile'):
                comment.nickname = request.user.userprofile.nickname
            else:
                comment.nickname = 'ADMIN'
            comment.save()
            return redirect('post', slug=slug)
    else:
        form = CommentForm()

    comments = Comment.objects.filter(post=post).order_by('-comment_added_date')
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'is_public': is_public,
    }
    return render(request, 'post.html', context)

@login_required
def private_post_view(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if post.privacy == 'private':
        if request.user != post.user:
            return HttpResponseForbidden("You don't have permission to access this page.")
    else:
        return redirect('post', slug=slug)

    return render(request, 'post.html', {'post': post, 'is_public': False})

@login_required
def add_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            if hasattr(request.user, 'userprofile'):
                comment.nickname = request.user.userprofile.nickname
            else:
                comment.nickname = 'ADMIN'
            comment.save()
            return redirect('post', slug=slug)
    else:
        form = CommentForm()

    comments = Comment.objects.filter(post=post).order_by('-comment_added_date')
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'post.html', context)

def search_view(request):
    query = request.GET.get('query')
    if query:
        tags = query.split()
        nicknames = query.split()
        title_condition = Q(title__icontains=query)
        content_condition = Q(content__icontains=query)
        nickname_condition = Q(user__userprofile__nickname__icontains=query)
        tag_conditions = Q()
        for tag in tags:
            tag_conditions |= Q(tags__name__iexact=tag)

        nickname_conditions = Q()
        for nickname in nicknames:
            nickname_conditions |= Q(user__userprofile__nickname__iexact=nickname)

        condition = (
            title_condition |
            content_condition |
            nickname_condition |
            tag_conditions |
            nickname_conditions
        )

        posts = Post.objects.filter(condition, privacy='public').distinct()

        if request.user.is_authenticated:
            is_admin_search = 'ADMIN' in query.upper()
            if is_admin_search:
                admin_posts = Post.objects.filter(
                    condition,
                    user__is_superuser=True
                ).distinct()
                posts = posts | admin_posts

            private_posts = Post.objects.filter(
                condition,
                Q(user=request.user, privacy='private') | nickname_conditions
            ).distinct()

            posts = posts | private_posts

        posts = posts.order_by('-post_added_date')

        paginator = Paginator(posts, 9)
        page_number = request.GET.get('page')
        paginated_posts = paginator.get_page(page_number)

        context = {
            'query': query,
            'posts': paginated_posts,
        }
        return render(request, 'search.html', context)
    else:
        return render(request, 'search.html')

blog/body/templates/body/account.html
{% extends 'body/welcome.html' %}
{% load static %}
{% block content %}
    <div class="background-image"></div>
    <div class="account-page">
        <div class="login-form">
            <h2>Welcome, {{ user_profile.user.username }}!</h2>
            <p>Email: {{ user_profile.user.email }}</p>
            <p>Nickname: {{ user_profile.nickname }}</p>
            <p>User since {{ registration_date|date:"F d, Y" }}, {{ registration_date|date:"H:i" }}</p>
            <div class="button-container">
                <button onclick="location.href='/'" type="button" class="home-button">
                    <i class="fa-solid fa-house" style="color: white;"></i>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

blog/body/templates/body/authors.html
{% extends 'body/welcome.html' %}
{% load static %}
{% block content %}
    <div class="background-image"></div>
    <div class="account-page">
        <div class="login-form">
            <div class="form-header">
                <div class="logo-container">
                    <img src="{% static 'PenSpotLogo.png' %}" alt="Logo">
                </div>
                <div class="form-content authors">
                    <div class="divider"></div>
                    <h2>Authors:</h2>
                    <div class="author">
                        <h3>Kacper Tomaszewski</h3>
                    </div>
                    <div class="author">
                        <h3>Szymon Trybułowski</h3>
                    </div>
                    <div class="author">
                        <h3>Mateusz Szabłowski</h3>
                    </div>
                    <div class="button-container">
                        <button onclick="location.href='/'"; type="button" class="home-button">
                            <i class="fa-solid fa-house" style="color: white;"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/body/templates/body/frontpage.html
{% extends 'body/welcome.html' %}
{% load static %}
{% block content %}
    <div class="frontpage-wrapper">
        <div class="navbar">
            <div class="logo">
                <img src="{% static 'PenSpotLogo.png' %}" alt="Logo">
            </div>
            <div class="navigation">
                <div class="account-buttons">
                    <button class="nav-button" onclick="location.href='latestposts/'">
                        <i class="fa-solid fa-list-ul"></i>
                    </button>
                    {% if is_user_logged_in %}
                        <button class="nav-button" onclick="location.href='newpost/'">
                            <i class="fa-solid fa-square-plus"></i>
                        </button>
                    {% endif %}
                    <button class="nav-button" onclick="location.reload()">
                        <i class="fa-solid fa-shuffle"></i>
                    </button>
                    <button class="nav-button" onclick="location.href='authors/'">
                        <i class="fa-solid fa-circle-question"></i>
                    </button>
                </div>
            </div>
            <div class="search-container">
                <form class="search-form" action="{% url 'search' %}" method="GET">
                    <input type="text" name="query" placeholder="Search by nickname or tags without '#'">
                    <button type="submit">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                </form>
            </div>
            <div class="account-buttons">
                {% if is_user_logged_in %}
                    <button onclick="location.href='account/'">
                        <i class="fa-solid fa-user"></i>
                    </button>
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button id="logout-button" onclick="logoutUser()">
                            <i class="fa-solid fa-power-off"></i>
                        </button>
                    </form>
                {% else %}
                    <button onclick="location.href='login/'">
                        <i class="fa-solid fa-sign-in"></i>
                    </button>
                {% endif %}
                <button onclick="location.href='admin/'">
                    <i class="fa-solid fa-user-secret"></i>
                </button>
            </div>
        </div>
        <script src="{% static 'logout.js' %}"></script>
        <div class="random-post-wrapper">
            <div class="random-post">
                <h3>Here's an example post on our website</h3>
                {% if random_post %}
                    {% if random_post.image %}
                        <div class="post-image post-image-large">
                            <img src="{{ random_post.image.url }}" alt="Post Image">
                        </div>
                    {% endif %}
                    <div class="post-details post-details-post-page">
                        <h2>{{ random_post.title }}</h2>
                        <p>Posted by {% if random_post.user.is_superuser %}<em>ADMIN</em>{% else %}<em>{{ random_post.user.userprofile.nickname }}</em>{% endif %}</p>
                        {% if random_post.privacy == 'public' or is_user_logged_in %}
                            <div class="post-content">
                                <p>{{ random_post.content }}</p>
                            </div>
                        {% else %}
                            <p>This is a private publication. Please log in to see the content.</p>
                        {% endif %}
                    </div>
                {% else %}
                    <p>No available publications.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

blog/body/templates/body/latestposts.html
{% extends 'body/welcome.html' %}
{% load static %}
{% block content %}
    <div class="latest-posts-wrapper content-wrapper">
        <h1 class="latest-posts-title">Latest Posts</h1>
        <div class="latest-posts-container">
            {% for post in latestposts %}
                {% if user.is_authenticated %}
                    {% if post.privacy == 'public' or post.privacy == 'private' %}
                        <div class="post" onclick="window.location.href='{% url 'post' slug=post.slug %}'">
                            <div class="post-image">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="Post Image">
                                {% else %}
                                    <img src="{% static 'noimage.jpg' %}" alt="No Image">
                                {% endif %}
                            </div>
                            <div class="post-details">
                                <h2>{{ post.title }}</h2>
                                {% if post.user.is_superuser %}
                                    <p class="author-info">Posted by <em>ADMIN</em></p>
                                {% else %}
                                    <p class="author-info">Posted by <em>{{ post.user.userprofile.nickname }}</em></p>
                                {% endif %}
                                <p class="tags">Tags:
                                    {% for tag in post.tags.all %}
                                        <a href="{% url 'tag_posts' tag_name=tag.name %}">#{{ tag.name }}</a>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                {% else %}
                    {% if post.privacy == 'public' %}
                        <div class="post" onclick="window.location.href='{% url 'post' slug=post.slug %}'">
                            <div class="post-image">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="Post Image">
                                {% else %}
                                    <img src="{% static 'noimage.jpg' %}" alt="No Image">
                                {% endif %}
                            </div>
                            <div class="post-details">
                                <h2>{{ post.title }}</h2>
                                {% if post.user.is_superuser %}
                                    <p class="author-info">Posted by <em>ADMIN</em></p>
                                {% else %}
                                    <p class="author-info">Posted by <em>{{ post.user.userprofile.nickname }}</em></p>
                                {% endif %}
                                <p class="tags">Tags:
                                    {% for tag in post.tags.all %}
                                        <a href="{% url 'tag_posts' tag_name=tag.name %}">#{{ tag.name }}</a>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
        <div class="pagination">
            <a href="{% url 'frontpage' %}" class="home-link"><i class="fas fa-home"></i></a>
            {% if latestposts.has_previous %}
                <a href="?page=1"><i class="fas fa-angle-double-left"></i></a>
                <a href="?page={{ latestposts.previous_page_number }}"><i class="fas fa-angle-left"></i></a>
            {% endif %}
            <span class="current-page">{{ latestposts.number }}</span>
            {% if latestposts.has_next %}
                <a href="?page={{ latestposts.next_page_number }}"><i class="fas fa-angle-right"></i></a>
                <a href="?page={{ latestposts.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i></a>
            {% endif %}
        </div>
    </div>
{% endblock %}

blog/body/templates/body/login.html
{% extends 'body/welcome.html' %}
{% load static %}
{% block content %}
    <div class="background-image"></div>
    <div class="login-page">
        <form class="login-form" method="POST">
            {% csrf_token %}
            <h2>Login</h2>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <p class="error-message">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div class="form-field">
                <label for="id_username">Username:</label>
                <input type="text" name="username" id="id_username" class="form-control" required>
                {% if form.errors.username %}
                    <p class="error-message">{{ form.errors.username }}</p>
                {% endif %}
            </div>
            <div class="form-field">
                <label for="id_password">Password:</label>
                <input type="password" name="password" id="id_password" class="form-control" required>
                {% if form.errors.password %}
                    <p class="error-message">{{ form.errors.password }}</p>
                {% endif %}
            </div>
            <div class="button-container">
                <button onclick="location.href='/register/'" type="button" class="signup-button">
                    <i class="fa-solid fa-user-plus" style="color: white;"></i>
                </button>
                <button onclick="location.href='/'"; type="button" class="home-button">
                    <i class="fa-solid fa-house" style="color: white;"></i>
                </button>
                <button type="submit" class="login-button">
                    <i class="fa-solid fa-sign-in" style="color: white;"></i>
                </button>
            </div>
        </form>
    </div>
{% endblock %}

blog/body/templates/body/register.html
{% extends 'body/welcome.html' %}
{% load static %}

{% block content %}
    <div class="background-image"></div>
    <div class="login-page">
        <form class="register-form" method="POST">
            {% csrf_token %}
            <h2>Register</h2>
            <div class="form-field">
                <label for="id_username">Username:</label>
                <input type="text" name="username" id="id_username" required>
            </div>
            <div class="form-field">
                <label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email" required>
            </div>
            <div class="form-field">
                <label for="id_nickname">Nickname:</label>
                <input type="text" name="nickname" id="id_nickname" required>
            </div>
            <div class="form-field">
                <label for="id_password">Password:</label>
                <input type="password" name="password" id="id_password" required>
            </div>
            <div class="form-field">
                <label for="id_confirm_password">Confirm Password:</label>
                <input type="password" name="confirm_password" id="id_confirm_password" required>
                {% if form.errors.confirm_password %}
                    <div class="error-message">{{ form.errors.confirm_password }}</div>
                {% endif %}
            </div>
            {% if error_message %}
                <div class="error-message">{{ error_message }}</div>
            {% endif %}
            <div class="button-container">
                <button onclick="location.href='/login/'" type="button" class="back-button">
                    <i class="fa-solid fa-arrow-left" style="color: white;"></i>
                </button>
                <button onclick="location.href='/'"; type="button" class="home-button">
                    <i class="fa-solid fa-house" style="color: white;"></i>
                </button>
                <button type="submit" class="signup-button">
                    <i class="fa-solid fa-user-plus" style="color: white;"></i>
                </button>
            </div>
        </form>
    </div>
{% endblock %}

blog/body/templates/body/welcome.html
{% load static %}
<!DOCTYPE html>

<html>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blog</title>
        <link rel="preload" href="{% static 'login-background1.jpg' %}" as="image">
        <link rel="preload" href="{% static 'login-background2.jpg' %}" as="image">
        <link rel="preload" href="{% static 'login-background3.jpg' %}" as="image">
        <link rel="preload" href="{% static 'login-background4.jpg' %}" as="image">
        <link rel="preload" href="{% static 'login-background5.jpg' %}" as="image">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
        <script src="https://kit.fontawesome.com/985470051c.js" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock %}
    </body>

</html>